### ISSUE TITLE
Sirius Issue

### ISSUE THREAD

**Issue by ckskate** [PARobotics4511/Scorpio#1]
Hello guyz. I am vrrry conserned about the naim of the robot thiz year. it shud not b so stupd. it is not good. pck somthing beter plz.

**Comment by ckskate** [comment]
*Bump.*

This was never resolved

**Comment by wjwalcher** [comment]
This issue has been left as an exercise to the reader

**Comment by brendon-boldt** [comment]
Guys, you should really read this [lesson](http://www.latlmes.com/tech/git-hub-issues-etiquette-1) on good GitHub practices.

**Comment by wjwalcher** [comment]
About time.
